### PR TITLE
Indentation matters

### PR DESCRIPTION
**Pull request by marceloboeira**
* Several indentation adjustments
* Removing unnecessary utf-8 comments

### CODE REVIEW

**Comment by marvin52** [comment]
:+1:

**Comment by gabrielalmir10** [comment]
:+1:

**Comment by raphaelcuba** [comment]
:+1:

**Comment by raphaelcuba** [comment]
@marceloboeira can you resolve the merge conflicts?

**Comment by marceloboeira** [comment]
@raphaelcuba I'll take a look asap.

**Comment by dalthon** [comment]
This pull request is not needed anymore due to a refactor

**Pull request closed without merging**
