### PR TITLE
Tidying up

### LINKED ISSUE #8: remover monkey patchs de Array e Hash
eles só são usados em 2 lugares(poderiam ser só métodos auxiliares ao invés de modificar diretamente as classes)

https://github.com/pagarme/pagarme-ruby/blob/master/lib/pagarme/util.rb#L63-L73

### PR DESCRIPTION
**Pull request by dalthon**
Merged these pull requests:

#25 update dates on tests so they pass.
#24 adding recipient support
#23 Add a simple Getting Started.
#22 Utils cleanup - Close #8
#20 Configurable Timeout Values
#14 improving error messages

Ignored this one:
#18 Indentation matters
Because is not needed anymore, code were reorganized from master since it this one was very old.

Issue 8 and 27 were solved.

### CODE REVIEW

**Comment by victorgama** [comment]
Would you mind to rebase your commits and fix the author information? You can force push to your branch. :shipit:

**Comment by dalthon** [comment]
Done! And decided to squash everything I did

**Comment by victorgama** [comment]
:shipit:

**Comment by thalesmello** [comment]
:shipit:

Atenciosamente,
Thales Mello.

**Pull request merged**
